### ISSUE TITLE
about multi-class tracking

### ISSUE THREAD

**Issue by BackT0TheFuture** [Vertical-Beach/ByteTrack-cpp#1]
Hi,
thanks for your efforts.
It seemed that it just did support single class tracking.
I'm not famliar with cpp and let me know if I was wrong.
so is there a plan for multi class tracking?
thanks!

**Comment by medalotte** [comment]
Hi, @goodtogood.
The tracking process is implemented as `BYTETracker` class, and the class deals with only a single class.

The test of this repo is an example. This implementation is single-class tracking because only one instance is declared.

https://github.com/Vertical-Beach/ByteTrack-cpp/blob/e6ee5a1485bedd24e2b8d6411be5d8fef63a6c3e/test/test_BYTETracker.cpp#L121

If you would like to do multi-class tracking, declare `std::vector<byte_track::BYTETracker>` object and track each class in each of its elements.

**Comment by BackT0TheFuture** [comment]
Hi @medalotte 
I got it.  BTW, is BYTETracker thread safety?
thanks for your details!
